CREATE USER pelukapp WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'pelukapp';	
	
CREATE DATABASE pelukapp
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

GRANT TEMPORARY, CONNECT ON DATABASE pelukapp TO PUBLIC;

GRANT ALL ON DATABASE pelukapp TO postgres;

GRANT TEMPORARY ON DATABASE pelukapp TO pelukapp;
